# Docker compose of my project
# The order matter

services:

  # Front
  front:
    build: ./front
    ports:
      - 4200:4200
      - 49153:49153
    volumes:
      - ./front:/usr/src/app
    environment:
      - NODE_ENV=dev
    command: bash -c "npm start"
    depends_on:
      - back

  maildev:
    image: soulteary/maildev
    ports:
      - 1080:1080
      - 1025:1025

  # DB
  database:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=fr_administration_database
      - MYSQL_DEFAULT_AUTHENTICATION_PLUGIN=caching_sha2_password
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - 3306:3306
  
  # Back
  back: 
    build: ./back
    ports:
      - 3000:3000
    volumes:
      - ./back:/usr/src/app
    command: bash -c 'while !</dev/tcp/database/3306; do sleep 1; done; npm run start:dev'
    depends_on:
      - database
      - maildev
    environment:
      RABBITMQ_URL: amqp://rabbitmq

  rabbitmq:
    image: 'rabbitmq:management'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      
  quarkus-app:
    build: ./rabbitmq-quickstart-processor
    ports:
      - "8080:8080"
    environment:
      - FROM_EMAIL=no-reply@fradminservice.com
    depends_on:
      - back
      - rabbitmq

  # Grafana service
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3001:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana

  # # Gateway
  # nginx:
  #   build: ./nginx
  #   image: jbindel/fr_administration_gateway
  #   depends_on:
  #     - front
  #     - back
  #   ports:
  #     - 80:80
  
volumes:
  mysql-db:
    external: true
  grafana-data: