# Docker compose of my project
# The order matter

services:

  # DB
  database:
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=fr_administration_database
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - 3306:3306
  
  # Back
  back: 
    build: ./back
    ports:
      - 3000:3000
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules
    command: bash -c 'while !</dev/tcp/database/3306; do sleep 1; done; npm run start:dev'
    depends_on:
      - database
      
  # Front
  front:
    build: ./front
    ports:
      - 4200:4200
      - 49153:49153
    volumes:
      - ./front:/usr/src/app
    environment:
      - NODE_ENV=dev
    command: bash -c "npm start"
    depends_on:
      - back

  # # Gateway
  # nginx:
  #   build: ./nginx
  #   image: jbindel/fr_administration_gateway
  #   depends_on:
  #     - front
  #     - back
  #   ports:
  #     - 80:80
  
volumes:
  mysql-db:
    external: true