global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: 'nestjs'
    static_configs:
      - targets: ['back:3000']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']