# Parent image
FROM mysql:latest

# Environment variables
ENV MYSQL_ROOT_PASSWORD admin
ENV MYSQL_DATABASE fr_administration_database

# Run -v /path/on/host:/var/lib/mysql when running the container
VOLUME /var/lib/mysql

EXPOSE 3306